import { IconUpload, IconSparkle } from './icons.jsx';

export default function Hero({ onUploadClick, busy }) {
  return (
    <section className="mx-auto grid max-w-6xl gap-12 px-5 pb-16 pt-10 sm:px-8 sm:pt-16 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">
      {/* Left: copy */}
      <div className="animate-rise">
        <span className="inline-flex items-center gap-1.5 rounded-full bg-accent-tint px-3 py-1 text-xs font-semibold text-accent-dark">
          <IconSparkle className="h-3.5 w-3.5" />
          Built on Cloudinary, end to end
        </span>

        <h1 className="mt-5 font-display text-4xl font-bold leading-[1.05] tracking-tight text-stone-900 sm:text-6xl">
          One phone photo in.
          <br />
          A <span className="text-accent">full listing</span> out.
        </h1>

        <p className="mt-5 max-w-[46ch] text-base leading-relaxed text-stone-600 sm:text-lg">
          Dukaan Studio is a pocket photo studio for India's WhatsApp- and
          Instagram-first home sellers. Upload one so-so product shot and get a
          studio background, a crop pack sized for every platform, auto tags,
          a searchable catalog, and a shareable reel &mdash; all generated by
          Cloudinary, not a design team.
        </p>

        <div className="mt-8 flex flex-wrap items-center gap-4">
          <button
            onClick={onUploadClick}
            disabled={busy}
            className="press-feedback inline-flex items-center gap-2 rounded-full bg-accent px-6 py-3.5 font-display text-sm font-semibold text-white shadow-[0_12px_24px_-8px_rgba(191,91,46,0.55)] transition-colors hover:bg-accent-dark disabled:opacity-60"
          >
            <IconUpload className="h-4 w-4" />
            {busy ? 'Uploading…' : 'Add a product photo'}
          </button>
          <span className="text-xs text-stone-400">No card, no design team &mdash; just a photo.</span>
        </div>
      </div>

      {/* Right: abstract illustration - CSS/SVG only, no external imagery */}
      <div className="relative mx-auto hidden h-[360px] w-full max-w-md sm:block">
        <div
          className="animate-float absolute left-1/2 top-1/2 h-[220px] w-[170px] -translate-x-1/2 -translate-y-1/2 rounded-[28px] border border-stone-300 bg-white shadow-[0_30px_60px_-20px_rgba(28,25,23,0.35)]"
          style={{ '--tilt': '-3deg', animationDelay: '0s' }}
        >
          <div className="m-3 h-[70%] rounded-2xl bg-stone-200" />
          <div className="mx-3 mt-2 h-2 w-2/3 rounded-full bg-stone-200" />
          <div className="mx-3 mt-2 h-2 w-1/3 rounded-full bg-stone-100" />
        </div>

        <div
          className="animate-float absolute left-[18%] top-[8%] h-[150px] w-[110px] rounded-2xl border-2 border-accent bg-accent-tint shadow-lg"
          style={{ '--tilt': '-14deg', animationDelay: '0.6s' }}
        />
        <div
          className="animate-float absolute right-[10%] top-[14%] h-[100px] w-[150px] rounded-2xl border-2 border-accent bg-white shadow-lg"
          style={{ '--tilt': '9deg', animationDelay: '1.2s' }}
        />
        <div
          className="animate-float absolute bottom-[6%] right-[16%] h-[130px] w-[90px] rounded-2xl border-2 border-stone-900 bg-stone-900/95 shadow-lg"
          style={{ '--tilt': '13deg', animationDelay: '0.3s' }}
        />
        <div
          className="animate-float absolute bottom-[10%] left-[8%] h-[90px] w-[130px] rounded-2xl border-2 border-accent-dark bg-white shadow-lg"
          style={{ '--tilt': '-10deg', animationDelay: '0.9s' }}
        />
      </div>
    </section>
  );
}
